services:
  bot:
    env_file: [.env.production]
    command: ["python", "main.py", "-env", "prod"]

  jobs:
    env_file: [.env.production]
    command: ["python", "jobs_main.py", "-env", "prod"]

  postgres:
    deploy:
      replicas: 0
