services:
  bot:
    env_file: [.env.staging]
    command: ["python", "main.py", "-env", "staging"]

  jobs:
    env_file: [.env.staging]
    command: ["python", "jobs_main.py", "-env", "staging"]

  postgres:
    deploy:
      replicas: 0
